stages:
  - build
  - test

compile-win:
  stage: build
  tags: 
    - windows
  script:
    - xcopy * C:\Git\tracktable /E /H /Y
    - cd C:\TrackTable
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe" ALL_BUILD.vcxproj /t:Rebuild /p:Configuration=Release /m:8'

compile-macos:
  stage: build
  tags: 
    - macos
  script:
    - pwd
    - cp ~/Library/TrackTableBuildFiles/CMakeLists.txt .
    - cmake ./
    - make -j8
    
test-win:
  stage: test
  tags: 
    - windows
  when: always
  script:
    - cd C:\TrackTable
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe" RUN_TESTS.vcxproj'
    
test-macos:
  stage: test
  tags: 
    - macos
  when: always
  script:
    - pwd
    - ls
    - ctest