############################################################
# Ubuntu 20.04 - Focal Fossa
############################################################
ubuntu2004-setup:
  image: cee-gitlab.sandia.gov:4567/trajectory/tracktable/ubuntu:FocalFossa
  stage: setup
  tags:
    - ubuntu
    - docker
  script:
    - mkdir build_ubuntu2004
  artifacts:
    paths:
      - build_ubuntu2004
    expire_in: 1 hour

ubuntu2004-configure:
  image: cee-gitlab.sandia.gov:4567/trajectory/tracktable/ubuntu:FocalFossa
  stage: configure
  tags:
    - ubuntu
    - docker
  dependencies:
    - ubuntu2004-setup
  script:
    - cd build_ubuntu2004
    - cmake -GNinja -DBUILD_DOCUMENTATION_CXX_ONLY=ON ..
  artifacts:
    paths:
      - build_ubuntu2004
    expire_in: 1 hour

ubuntu2004-build:
  image: cee-gitlab.sandia.gov:4567/trajectory/tracktable/ubuntu:FocalFossa
  stage: build
  tags:
    - ubuntu
    - docker
  dependencies:
    - ubuntu2004-configure
  script:
    - cd build_ubuntu2004
    - ninja
  artifacts:
    paths:
      - build_ubuntu2004
    expire_in: 1 hour

ubuntu2004-test:
  image: cee-gitlab.sandia.gov:4567/trajectory/tracktable/ubuntu:FocalFossa
  stage: test
  tags:
    - ubuntu
    - docker
  dependencies:
    - ubuntu2004-build
  script:
    - cp build_ubuntu2004/lib/_*.so tracktable/Python/tracktable/lib/
    - cd build_ubuntu2004
    - ctest --output-on-failure --exclude-regex 'C_MemoryUse|C_GREAT_CIRCLE_FIT|P_Render_Trajectories'
  artifacts:
    paths:
      - build_ubuntu2004
    expire_in: 1 hour

