stages:
  - build
  - test

compile-win:
  stage: build
  tags: 
    - windows
  script: 
    - cd C:\TrackTable
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe" ALL_BUILD.vcxproj /t:Rebuild /p:Configuration=Release /m:8'
  only:
    - tags

# run tests using the binary built before
test-win:
  stage: test
  tags: 
    - windows
  script:
    - cd C:\TrackTable
    - msbuild RUN_TESTS.vcxproj
  only:
    - tags