############################################################
# Ubuntu 20.04 - Focal Fossa
############################################################
variables:
    UBUNTU_2004_DOCKER_IMAGE: cee-gitlab.sandia.gov:4567/trajectory/tracktable/ubuntu/20.04:2

.ubuntu2004-before: &ubuntu2004-before
    - . /root/miniconda3/etc/profile.d/conda.sh
    - conda activate tracktable-dev

ubuntu2004-setup:
  image: $UBUNTU_2004_DOCKER_IMAGE
  stage: setup
  tags:
    - ubuntu
    - docker
  before_script:
    - *ubuntu2004-before
  script:
    - mkdir build_ubuntu2004
  artifacts:
    paths:
      - build_ubuntu2004
    expire_in: 1 hour

ubuntu2004-configure:
  image: $UBUNTU_2004_DOCKER_IMAGE
  stage: configure
  tags:
    - ubuntu
    - docker
  dependencies:
    - ubuntu2004-setup
  needs:
    - job: ubuntu2004-setup
      artifacts: true
  before_script:
    - *ubuntu2004-before
  script:
    - cd build_ubuntu2004
    - cmake -GNinja -DBUILD_DOCUMENTATION_CXX_ONLY=ON ..
  artifacts:
    paths:
      - build_ubuntu2004
    expire_in: 1 hour

ubuntu2004-build:
  image: $UBUNTU_2004_DOCKER_IMAGE
  stage: build
  tags:
    - ubuntu
    - docker
  dependencies:
    - ubuntu2004-configure
  needs:
    - job: ubuntu2004-configure
      artifacts: true
  before_script:
    - *ubuntu2004-before
  script:
    - cd build_ubuntu2004
    - ninja
  artifacts:
    paths:
      - build_ubuntu2004
    expire_in: 1 hour

ubuntu2004-test:
  image: $UBUNTU_2004_DOCKER_IMAGE
  stage: test
  tags:
    - ubuntu
    - docker
  dependencies:
    - ubuntu2004-build
  needs:
    - job: ubuntu2004-build
      artifacts: true
  before_script:
    - *ubuntu2004-before
  script:
    - pip3 install --trusted-host pypi.org --trusted-host files.pythonhosted.org tracktable-data # TODO (mjfadem): This is a band-aid fix for right now
    - cp build_ubuntu2004/lib/_*.so tracktable/Python/tracktable/lib/
    - cd build_ubuntu2004
    - ctest --output-on-failure --exclude-regex 'C_GREAT_CIRCLE_FIT|C_MemoryUse|C_PointGenerator|P_TerrestrialHeatmapExample|P_TerrestrialTrajectoryMapExample|P_Mapmaker_CONUS|P_Mapmaker_Custom_Bounding_Box_Object|P_Mapmaker_Custom_Bounding_Box_Floats|P_Mapmaker_Europe|P_Render_Trajectories'
  artifacts:
    paths:
      - build_ubuntu2004
    expire_in: 1 hour

