############################################################
# Code Coverage pipeline: uses ubuntu Focal Fossa
############################################################
coverage-setup:
  image: cee-gitlab.sandia.gov:4567/trajectory/tracktable/ubuntu:FocalFossa
  stage: setup
  rules:
    - if: $DO_COVERAGE == "true"
  tags:
    - linux
  script:
    - mkdir build_coverage
  artifacts:
    paths:
      - build_coverage
    expire_in: 2 hours

coverage-configure:
  image: cee-gitlab.sandia.gov:4567/trajectory/tracktable/ubuntu:FocalFossa
  stage: configure
  rules:
    - if: $DO_COVERAGE == "true"
  tags:
    - linux
  dependencies:
    - coverage-setup
  script:
    - apt-get update
    - apt-get -y install lcov
    - cd build_coverage
    - cmake -DCMAKE_BUILD_TYPE=Coverage ..
  artifacts:
    paths:
      - build_coverage
    expire_in: 2 hours

coverage-build:
  image: cee-gitlab.sandia.gov:4567/trajectory/tracktable/ubuntu:FocalFossa
  stage: build
  rules:
    - if: $DO_COVERAGE == "true"
  tags:
    - linux
  dependencies:
    - coverage-configure
  script:
    - apt-get update
    - apt-get -y install lcov
    - cd build_coverage
    - make
    - make cov_init
    - ctest --output-on-failure --exclude-regex 'C_GREAT_CIRCLE_FIT|C_MemoryUse|C_PointGenerator|P_TerrestrialHeatmapExample|P_TerrestrialTrajectoryMapExample|P_Mapmaker_CONUS|P_Mapmaker_Custom_Bounding_Box_Object|P_Mapmaker_Custom_Bounding_Box_Floats|P_Mapmaker_Europe|P_Render_Trajectories'
    - make cov_capture
    - make cov_genhtml
  artifacts:
    paths:
      - build_coverage
    expire_in: 1 week
