stages:
  - code analysis
  - setup
  - configure
  - build
  - test

variables:
  # This is a regular expression that identifies tests that CTest
  # should skip.  We use this for problematic tests that fail for
  # reasons unrelated to problems with the code -- that is, tests
  # that themselves are buggy.
    EXCLUDED_TESTS: "C_MemoryUse|C_GREAT_CIRCLE_FIT|P_Render_Trajectories|P_Mapmaker_CONUS|P_Mapmaker_Custom_Bounding_Box_Object|P_Mapmaker_Custom_Bounding_Box_Floats|P_Mapmaker_Europe"
  # This is a switch for determining whether or not to run the
  # code coverage pipeline.  Combined with a schedule on "develop", this
  # should allow us to do code coverage once a week at an innocuous time
    DO_COVERAGE: "false"

include:
  - '.gitlab-ci-code_analysis.yml'
  - '.gitlab-ci-windows.yml'
  - '.gitlab-ci-macos.yml'
  - '.gitlab-ci-ubuntu2004.yml'
  - '.gitlab-ci-coverage.yml'
