stages:
  - code analysis
  - setup
  - configure
  - build
  - test
  - deploy

variables:
# This is a regular expression that identifies tests that CTest
  # should skip.  We use this for problematic tests that fail for
  # reasons unrelated to problems with the code -- that is, tests
  # that themselves are buggy.
  EXCLUDED_TESTS: "C_MemoryUse|C_GREAT_CIRCLE_FIT|P_Render_Trajectories|P_Mapmaker_CONUS|P_Mapmaker_Custom_Bounding_Box_Object|P_Mapmaker_Custom_Bounding_Box_Floats|P_Mapmaker_Europe"
  GIT_SUBMODULE_STRATEGY: recursive

include:
  - '.gitlab-ci-code_analysis.yml'
  - '.gitlab-ci-windows.yml'
  - '.gitlab-ci-macos.yml'
  - '.gitlab-ci-linux.yml'
