# Configuration file for building documentation on readthedocs.org

# Ordinarily, Tracktable expects all of its build configuration to be
# done by CMake, including the hassle of filling out paths that are
# only known at runtime.
#
# ReadTheDocs doesn't use CMake.  (Thank goodness.)  It wants to be
# able to build straight from a newly cloned repository whenever
# possible using settings common to most pure-Python projects.
#
# This file contains configuration options to reach a happy medium.
#
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for
# details.

# Required tag
version: 2

# Build documentation in the Documentation/ directory using Sphinx.
sphinx:
  fail_on_warning: false
  configuration: Documentation/conf.py

# Eventually we will also build docs as PDF and ePub.
# formats: all

# The Docker image for building the docs
build:
  image: latest

# The Anaconda environment to build the docs
conda:
  environment: environment.yml
