# Conda environment for readthedocs.io
#
# When we upload documentation to readthedocs, it gets
# built inside a Conda environment.  This file specifies
# that environment's contents.  It is stripped down to 
# what we believe is a minimal set of requirements.

name: tracktable-readthedocs
channels:
  - conda-forge
dependencies:
  # Python Dependencies
  - python>=3.10
  - matplotlib>=3.0
  - scipy>=1.5.2
  - tracktable
  - tracktable-data>=1.7.0
  - pip
  
  # Jupyter Dependencies
  - ipykernel
  - jupyter

  # Documentation Dependencies
  - sphinx>=3.4.3
  - sphinx_rtd_theme>=0.5.0
  - nbsphinx>=0.7.1
  - nbsphinx-link>=1.3.0
  - pandoc>=2.5
  - doxygen>=1.8.17
  - graphviz>=2.42.2
  - breathe>=4.26.1, <=4.31.0
