# Conda environment for readthedocs.io
#
# When we upload documentation to readthedocs, it gets
# built inside a Conda environment.  This file specifies
# that environment's contents.  It is stripped down to
# what we believe is a minimal set of requirements.

name: tracktable-readthedocs
channels:
  - conda-forge
dependencies:
  # Git Dependencies
  - git
  - git-lfs

  # Python Dependencies
  - python>=3.10
  - matplotlib>=3.0
  - scipy>=1.5.2
  - tracktable
  - tracktable-data>=1.7.3
  - pip

  # Jupyter Dependencies
  - ipykernel
  - jupyter

  # Documentation Dependencies
  - sphinx>=8.0
  - sphinx_rtd_theme
  - nbsphinx>=0.7.1
  - pandoc>=2.5
  - doxygen
  - graphviz>=2.42.2
  - breathe
  - pip:
    - nbsphinx-link>=1.3.1
