name: tracktable
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - tracktable-data
  - ipykernel
  - pandoc
  - sphinx<4.1.0 # Issues with C++ and templates with newer versions
  - pip:
    - breathe
    - nbsphinx
    - nbsphinx-link