name: tracktable
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - numpy
  - pytz
  - cartopy
  - pyshp
  - ipykernel
  - pandoc
  - sphinx
  - pip:
    - tracktable
    - breathe
    - nbsphinx
    - nbsphinx-link
