name: tracktable
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - tracktable-data
  - ipykernel
  - pandoc
  - sphinx # Lock version to 4.1.0 if there are issues with C++ and templates
  - graphviz>=2.42.2
  - breathe>=4.26.1, <=4.31.0
  - nbsphinx>=0.7.1
  - nbsphinx-link>=1.3.0